version: "3.0"

expectations:
  population_size: 100000

actions:
  generate_cohort_2019:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-02-01" 
    outputs:
      highly_sensitive:
        cohort: output/input_2019-02-01.csv

  generate_cohort_2020:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-02-01" 
    outputs:
      highly_sensitive:
        cohort: output/input_2020-02-01.csv

  generate_measures_cohorts:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_measures --index-date-range "2019-02-01 to 2021-02-01 by month"
    outputs:
      highly_sensitive:
        cohort_measures: output/input_measures_*.csv

  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition_measures
    needs: [generate_measures_cohorts]
    outputs:
      moderately_sensitive:
        measure1: output/measure_covid_death_age.csv
        measure2: output/measure_allcause_death_age.csv
        measure3: output/measure_noncovid_death_age.csv
        measure4: output/measure_covid_death_sex_age_five.csv
        measure5: output/measure_allcause_death_sex_age_five.csv
        measure6: output/measure_noncovid_death_sex_age_five.csv
        measure7: output/measure_covid_death_age_chdetail.csv
        measure8: output/measure_allcause_death_age_chdetail.csv
        measure9: output/measure_noncovid_death_age_chdetail.csv
        measure10: output/measure_tpp_death_age.csv

  010_data_management_2019:
    run: r:latest analysis/010_data_management.R ./output/input_2019-02-01.csv ./output/study_population_2019.csv
    needs: [generate_cohort_2019]
    outputs: 
      highly_sensitive:
        data1: output/study_population_2019.csv

  010_data_management_2020:
    run: r:latest analysis/010_data_management.R ./output/input_2020-02-01.csv ./output/study_population_2020.csv
    needs: [generate_cohort_2020]
    outputs: 
      highly_sensitive:
        data2: output/study_population_2020.csv

  020_baseline_characteristics_2019:
    run: r:latest analysis/020_baseline_characteristics.R ./output/study_population_2019.csv ./output/tables/table_1_2019.txt
    needs: [generate_cohort_2019, 010_data_management_2019]
    outputs: 
      moderately_sensitive:
        table1a: output/tables/table_1_2019.txt

  020_baseline_characteristics_2020:
    run: r:latest analysis/020_baseline_characteristics.R ./output/study_population_2020.csv ./output/tables/table_one_2020.txt
    needs: [generate_cohort_2020, 010_data_management_2020]
    outputs: 
      moderately_sensitive:
        table1b: output/tables/table_one_2020.txt

  030_descriptive_mortality_rates.R:
    run: r:latest analysis/030_descriptive_mortality_rates.R 
    needs: [generate_measures_cohorts, generate_measures]
    outputs: 
      moderately_sensitive:
        table_descriptive_allcause: output/tables/table_descriptive_allcause.txt
        table_descriptive_covid: output/tables/table_descriptive_covid.txt
        table_descriptive_noncovid: output/tables/table_descriptive_noncovid.txt
        plot_descriptive_allcause: output/plots/plot_descriptive_allcause.png
        plot_descriptive_covid: output/plots/plot_descriptive_covid.png
        plot_descriptive_noncovid: output/plots/plot_descriptive_noncovid.png


  035_comparative_mortality_rates.R:
    run: r:latest analysis/035_comparative_mortality_rates.R 
    needs: [generate_measures_cohorts, generate_measures]
    outputs: 
      moderately_sensitive:
        table_comparative_allcause: output/tables/table_comparative_allcause.txt
        table_comparative_covid: output/tables/table_comparative_covid.txt
        table_noncomparative_covid: output/tables/table_noncomparative_covid.txt
        plot_comparative_allcause: output/plots/plot_comparative_allcause.png
        plot_comparative_covid: output/plots/plot_comparative_covid.png
        plot_comparative_noncovid: output/plots/plot_comparative_noncovid.png

  040_cause_of_death.R:
    run: r:latest analysis/040_cause_of_death.R 
    needs: [generate_measures_cohorts]
    outputs: 
      moderately_sensitive:
        table_allcauses_ch: output/tables/table_allcauses_ch.txt
        table_allcauses_ph: output/tables/table_allcauses_ph.txt
        table_nccauses_ch: output/tables/table_nccauses_ch.txt
        table_nccauses_ph: output/tables/table_nccauses_ph.txt
        plot_allcauses_ch: output/plots/plot_allcauses_ch.png
        plot_allcauses_ph: output/plots/plot_allcauses_ph.png
        plot_nccauses_ch: output/plots/plot_nccauses_ch.png
        plot_nccauses_ph: output/plots/plot_nccauses_ph.png

  050_standardisation.R:
    run: r:latest analysis/050_standardisation.R 
    needs: [generate_measures_cohorts, generate_measures]
    outputs: 
      moderately_sensitive:
        table_standardised_allcause: output/tables/table_standardised_allcause.txt
        table_standardised_covid: output/tables/table_standardised_covid.txt
        table_standardised_noncovid: output/tables/table_standardised_noncovid.txt     
        plot_standardised_allcause: output/plots/plot_standardised_allcause.png
        plot_standardised_covid: output/plots/plot_standardised_covid.png
        plot_standardised_noncovid: output/plots/plot_standardised_noncovid.png
        table_cmr_allcause: output/tables/table_cmr_allcause.txt
        table_cmr_covid: output/tables/table_cmr_covid.txt
        table_cmr_noncovid: output/tables/table_cmr_noncovid.txt
        plot_cmr_allcause: output/plots/plot_cmr_allcause.png
        plot_cmr_covid: output/plots/plot_cmr_covid.png
        plot_cmr_noncovid: output/plots/plot_cmr_noncovid.png


