version: "3.0"

expectations:
  population_size: 1000

actions:
  generate_cohort_2019:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_2019
    outputs:
      highly_sensitive:
        cohort: output/input_2019.csv

  generate_cohort_2020:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_2020
    outputs:
      highly_sensitive:
        cohort: output/input_2020.csv

  generate_measures_cohorts:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_measures --index-date-range "2020-02-01 to 2020-04-01 by week"
    outputs:
      highly_sensitive:
        cohort1: output/input_measures_*.csv

  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition_measures
    needs: [generate_measures_cohorts]
    outputs:
      moderately_sensitive:
        measure1: output/measure_covid_death_all.csv
        measure2: output/measure_covid_death_sex.csv
        measure3: output/measure_covid_death_age.csv
        measure4: output/measure_covid_death_sex_age.csv
        measure5: output/measure_allcause_death_all.csv
        measure6: output/measure_allcause_death_sex.csv
        measure7: output/measure_allcause_death_age.csv
        measure8: output/measure_allcause_death_sex_age.csv
        measure9: output/measure_noncovid_death_all.csv
        measure10: output/measure_noncovid_death_sex.csv
        measure11: output/measure_noncovid_death_age.csv
        measure12: output/measure_noncovid_death_sex_age.csv

  010_data_management_2019:
    run: r:latest analysis/010_data_management.R ./output/input_2019.csv 20190201 ./data/study_population_2019.csv
    needs: [generate_cohort_2019]
    outputs: 
      highly_sensitive:
        data1: data/study_population_2019.csv

  010_data_management_2020:
    run: r:latest analysis/010_data_management.R ./output/input_2020.csv 20200201 ./data/study_population_2020.csv
    needs: [generate_cohort_2020]
    outputs: 
      highly_sensitive:
        data2: data/study_population_2020.csv

  020_baseline_characteristics_2019:
    run: r:latest analysis/020_baseline_characteristics.R ./data/study_population_2019.csv ./analysis/outfiles/table_1a.txt
    needs: [generate_cohort_2019, 010_data_management_2019]
    outputs: 
      moderately_sensitive:
        table1a: analysis/outfiles/table_1a.txt

  020_baseline_characteristics_2020:
    run: r:latest analysis/020_baseline_characteristics.R ./data/study_population_2020.csv ./analysis/outfiles/table_1b.txt
    needs: [generate_cohort_2020, 010_data_management_2020]
    outputs: 
      moderately_sensitive:
        table1b: analysis/outfiles/table_1b.txt

  025_carehome_characteristics:
    run: r:latest analysis/025_carehome_characteristics.R ./data/study_population_2020.csv 
    needs: [010_data_management_2020]
    outputs: 
      moderately_sensitive:
        log: analysis/outfiles/carehome_characteristics.txt

  030_descriptive_mortality_rates.R:
    run: r:latest analysis/030_descriptive_mortality_rates.R 
    needs: [generate_measures_cohorts, generate_measures]
    outputs: 
      moderately_sensitive:
        table_2a: analysis/outfiles/table_2a.txt
        table_2b: analysis/outfiles/table_2b.txt
        table_2c: analysis/outfiles/table_2c.txt
        table_2d: analysis/outfiles/table_2d.txt
        table_3a: analysis/outfiles/table_3a.txt
        table_3b: analysis/outfiles/table_3b.txt
        table_3c: analysis/outfiles/table_3c.txt
        table_3d: analysis/outfiles/table_3d.txt
        table_4a: analysis/outfiles/table_4a.txt
        table_4b: analysis/outfiles/table_4b.txt
        table_4c: analysis/outfiles/table_4c.txt
        table_4d: analysis/outfiles/table_4d.txt
        plot_1a: analysis/outfiles/plot_1a.png
        plot_1b: analysis/outfiles/plot_1b.png
        plot_1c: analysis/outfiles/plot_1c.png
        plot_2a: analysis/outfiles/plot_2a.png
        plot_2b: analysis/outfiles/plot_2b.png
        plot_2c: analysis/outfiles/plot_2c.png
        plot_3a: analysis/outfiles/plot_3a.png
        plot_3b: analysis/outfiles/plot_3b.png
        plot_3c: analysis/outfiles/plot_3c.png

  035_comparative_mortality_rates.R:
    run: r:latest analysis/035_comparative_mortality_rates.R 
    needs: [generate_measures_cohorts, generate_measures]
    outputs: 
      moderately_sensitive:
        table_2a: analysis/outfiles/table_5a.txt
        table_2b: analysis/outfiles/table_5b.txt
        table_2c: analysis/outfiles/table_5c.txt
        table_2d: analysis/outfiles/table_5d.txt
        table_3a: analysis/outfiles/table_6a.txt
        table_3b: analysis/outfiles/table_6b.txt
        table_3c: analysis/outfiles/table_6c.txt
        table_3d: analysis/outfiles/table_6d.txt
        table_4a: analysis/outfiles/table_7a.txt
        table_4b: analysis/outfiles/table_7b.txt
        table_4c: analysis/outfiles/table_7c.txt
        table_4d: analysis/outfiles/table_7d.txt
        plot_1a: analysis/outfiles/plot_4a.png
        plot_1b: analysis/outfiles/plot_4b.png
        plot_1c: analysis/outfiles/plot_4c.png
        plot_2a: analysis/outfiles/plot_5a.png
        plot_2b: analysis/outfiles/plot_5b.png
        plot_2c: analysis/outfiles/plot_5c.png
        plot_3a: analysis/outfiles/plot_6a.png
        plot_3b: analysis/outfiles/plot_6b.png
        plot_3c: analysis/outfiles/plot_6c.png
