version: "3.0"

expectations:
  population_size: 1000

actions:
  generate_cohort_2019:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_2019
    outputs:
      highly_sensitive:
        cohort: output/input_2019.csv

  generate_cohort_2020:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_2020
    outputs:
      highly_sensitive:
        cohort: output/input_2020.csv

  generate_measures_cohorts:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_measures --index-date-range "2019-02-01 to 2020-11-30 by month"
    outputs:
      highly_sensitive:
        cohort1: output/input_measures_*.csv

  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition_measures
    needs: [generate_measures_cohorts]
    outputs:
      moderately_sensitive:
        measure1: output/measure_covid_death_all.csv
        measure2: output/measure_covid_death_sex.csv
        measure3: output/measure_covid_death_age.csv
        measure4: output/measure_covid_death_sex_age.csv
        measure5: output/measure_allcause_death_all.csv
        measure6: output/measure_allcause_death_sex.csv
        measure7: output/measure_allcause_death_age.csv
        measure8: output/measure_allcause_death_sex_age.csv
        measure9: output/measure_noncovid_death_all.csv
        measure10: output/measure_noncovid_death_sex.csv
        measure11: output/measure_noncovid_death_age.csv
        measure12: output/measure_noncovid_death_sex_age.csv
        measure13: output/measure_covid_death_sex_age_five.csv
        measure14: output/measure_allcause_death_sex_age_five.csv
        measure15: output/measure_noncovid_death_sex_age_five.csv
        measure16: output/measure_covid_death_all_chdetail.csv
        measure17: output/measure_covid_death_sex_chdetail.csv
        measure18: output/measure_covid_death_age_chdetail.csv
        measure19: output/measure_covid_death_sex_age_chdetail.csv
        measure20: output/measure_allcause_death_all_chdetail.csv
        measure21: output/measure_allcause_death_sex_chdetail.csv
        measure22: output/measure_allcause_death_age_chdetail.csv
        measure23: output/measure_allcause_death_sex_age_chdetail.csv
        measure24: output/measure_noncovid_death_all_chdetail.csv
        measure25: output/measure_noncovid_death_sex_chdetail.csv
        measure26: output/measure_noncovid_death_age_chdetail.csv
        measure27: output/measure_noncovid_death_sex_age_chdetail.csv

  010_data_management_2019:
    run: r:latest analysis/010_data_management.R ./output/input_2019.csv ./data/study_population_2019.csv
    needs: [generate_cohort_2019]
    outputs: 
      highly_sensitive:
        data1: data/study_population_2019.csv

  010_data_management_2020:
    run: r:latest analysis/010_data_management.R ./output/input_2020.csv ./data/study_population_2020.csv
    needs: [generate_cohort_2020]
    outputs: 
      highly_sensitive:
        data2: data/study_population_2020.csv

  020_baseline_characteristics_2019:
    run: r:latest analysis/020_baseline_characteristics.R ./data/study_population_2019.csv ./analysis/outfiles/table_1a.txt
    needs: [generate_cohort_2019, 010_data_management_2019]
    outputs: 
      moderately_sensitive:
        table1a: analysis/outfiles/table_1a.txt

  020_baseline_characteristics_2020:
    run: r:latest analysis/020_baseline_characteristics.R ./data/study_population_2020.csv ./analysis/outfiles/table_1b.txt
    needs: [generate_cohort_2020, 010_data_management_2020]
    outputs: 
      moderately_sensitive:
        table1b: analysis/outfiles/table_1b.txt

  025_carehome_characteristics:
    run: r:latest analysis/025_carehome_characteristics.R ./data/study_population_2020.csv 
    needs: [010_data_management_2020]
    outputs: 
      moderately_sensitive:
        log: analysis/outfiles/carehome_characteristics.txt

  030_descriptive_mortality_rates.R:
    run: r:latest analysis/030_descriptive_mortality_rates.R 
    needs: [generate_measures_cohorts, generate_measures]
    outputs: 
      moderately_sensitive:
        table_2a: analysis/outfiles/table_2a.txt
        table_2b: analysis/outfiles/table_2b.txt
        table_2c: analysis/outfiles/table_2c.txt
        table_2d: analysis/outfiles/table_2d.txt
        table_3a: analysis/outfiles/table_3a.txt
        table_3b: analysis/outfiles/table_3b.txt
        table_3c: analysis/outfiles/table_3c.txt
        table_3d: analysis/outfiles/table_3d.txt
        table_4a: analysis/outfiles/table_4a.txt
        table_4b: analysis/outfiles/table_4b.txt
        table_4c: analysis/outfiles/table_4c.txt
        table_4d: analysis/outfiles/table_4d.txt
        plot_1a: analysis/outfiles/plot_1a.png
        plot_1b: analysis/outfiles/plot_1b.png
        plot_1c: analysis/outfiles/plot_1c.png
        plot_2a: analysis/outfiles/plot_2a.png
        plot_2b: analysis/outfiles/plot_2b.png
        plot_2c: analysis/outfiles/plot_2c.png
        plot_3a: analysis/outfiles/plot_3a.png
        plot_3b: analysis/outfiles/plot_3b.png
        plot_3c: analysis/outfiles/plot_3c.png

  035_comparative_mortality_rates.R:
    run: r:latest analysis/035_comparative_mortality_rates.R 
    needs: [generate_measures_cohorts, generate_measures]
    outputs: 
      moderately_sensitive:
        table_5a: analysis/outfiles/table_5a.txt
        table_5b: analysis/outfiles/table_5b.txt
        table_5c: analysis/outfiles/table_5c.txt
        table_5d: analysis/outfiles/table_5d.txt
        table_6a: analysis/outfiles/table_6a.txt
        table_6b: analysis/outfiles/table_6b.txt
        table_6c: analysis/outfiles/table_6c.txt
        table_6d: analysis/outfiles/table_6d.txt
        table_7a: analysis/outfiles/table_7a.txt
        table_7b: analysis/outfiles/table_7b.txt
        table_7c: analysis/outfiles/table_7c.txt
        table_7d: analysis/outfiles/table_7d.txt
        plot_8a: analysis/outfiles/plot_4a.png
        plot_8b: analysis/outfiles/plot_4b.png
        plot_8c: analysis/outfiles/plot_4c.png
        plot_5a: analysis/outfiles/plot_5a.png
        plot_5b: analysis/outfiles/plot_5b.png
        plot_5c: analysis/outfiles/plot_5c.png
        plot_6a: analysis/outfiles/plot_6a.png
        plot_6b: analysis/outfiles/plot_6b.png
        plot_6c: analysis/outfiles/plot_6c.png

  040_cause_of_death.R:
    run: r:latest analysis/040_cause_of_death.R 
    needs: [generate_measures_cohorts]
    outputs: 
      moderately_sensitive:
        table_8a: analysis/outfiles/table_8a.txt
        table_8b: analysis/outfiles/table_8b.txt
        plot_7a: analysis/outfiles/plot_7a.png
        plot_7b: analysis/outfiles/plot_7b.png

  050_standardisation.R:
    run: r:latest analysis/050_standardisation.R 
    needs: [generate_measures_cohorts, generate_measures]
    outputs: 
      moderately_sensitive:
        table_9a: analysis/outfiles/table_9a.txt
        table_9b: analysis/outfiles/table_9b.txt     
        table_9c: analysis/outfiles/table_9c.txt
        plot_8a: analysis/outfiles/plot_8a.png
        plot_8b: analysis/outfiles/plot_8b.png
        plot_8c: analysis/outfiles/plot_8c.png

  generate_measures_sensitivity_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_measures_tppdeath --index-date-range "2016-02-01 to 2020-11-30 by month"
    outputs:
      highly_sensitive:
        cohort_sensitivity: output/input_measures_tppdeath_*.csv

  generate_measures_sensitivity:
    run: cohortextractor:latest generate_measures --study-definition study_definition_measures_tppdeath
    needs: [generate_measures_sensitivity_cohort]
    outputs:
      moderately_sensitive:
        measure_sensitivity: output/measure_allcause_tppdeath_all.csv
