version: "3.0"

expectations:
  population_size: 100000

actions:

# PRIMARY ANALYSES 
    
  generate_cohort_2019:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-02-01" 
    outputs:
      highly_sensitive:
        cohort: output/input_2019-02-01.csv

  generate_cohort_2020:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-02-01" 
    outputs:
      highly_sensitive:
        cohort: output/input_2020-02-01.csv

  generate_cohort_2wave:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-09-01" 
    outputs:
      highly_sensitive:
        cohort: output/input_2020-09-01.csv

  generate_cohort_2021:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2021-02-01" 
    outputs:
      highly_sensitive:
        cohort: output/input_2021-02-01.csv

  generate_measures_cohorts:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_measures --index-date-range "2019-02-01 to 2021-03-31 by month"
    outputs:
      highly_sensitive:
        cohort_measures: output/input_measures_*.csv

  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition_measures
    needs: [generate_measures_cohorts]
    outputs:
      highly_sensitive:
        measure1: output/measure_covid_death_age.csv
        measure2: output/measure_allcause_death_age.csv
        measure3: output/measure_noncovid_death_age.csv
        measure4: output/measure_covid_death_sex_age_five.csv
        measure5: output/measure_allcause_death_sex_age_five.csv
        measure6: output/measure_noncovid_death_sex_age_five.csv
        measure7: output/measure_covid_death_age_chdetail.csv
        measure8: output/measure_allcause_death_age_chdetail.csv
        measure9: output/measure_noncovid_death_age_chdetail.csv
        measure14: output/measure_tested_covid.csv
        measure15: output/measure_admitted_covid.csv
        measure16: output/measure_admitted_any.csv
        measure17: output/measure_tested_covid_age.csv
        measure18: output/measure_admitted_covid_age.csv
        measure19: output/measure_admitted_any_age.csv
        measure20: output/measure_admitted_noncovid.csv
        measure21: output/measure_admitted_noncovid_age.csv
                
  010_data_management_2019:
    run: r:latest analysis/010_data_management.R ./output/input_2019-02-01.csv ./output/study_population_2019.csv ./output/study_population_new_2019.csv
    needs: [generate_cohort_2019]
    outputs: 
      highly_sensitive:
        data1: output/study_population_2019.csv
        data1_new: output/study_population_new_2019.csv

  010_data_management_2020:
    run: r:latest analysis/010_data_management.R ./output/input_2020-02-01.csv ./output/study_population_2020.csv ./output/study_population_new_2020.csv
    needs: [generate_cohort_2020]
    outputs: 
      highly_sensitive:
        data2: output/study_population_2020.csv
        data2_new: output/study_population_new_2020.csv

  010_data_management_2wave:
    run: r:latest analysis/010_data_management.R ./output/input_2020-09-01.csv ./output/study_population_2wave.csv ./output/study_population_new_2wave.csv
    needs: [generate_cohort_2wave]
    outputs: 
      highly_sensitive:
        data3: output/study_population_2wave.csv
        data3_new: output/study_population_new_2wave.csv

  010_data_management_2021:
    run: r:latest analysis/010_data_management.R ./output/input_2021-02-01.csv ./output/study_population_2021.csv ./output/study_population_new_2021.csv
    needs: [generate_cohort_2021]
    outputs: 
      highly_sensitive:
        data4: output/study_population_2021.csv
        data4_new: output/study_population_new_2021.csv

  020_baseline_characteristics_2019:
    run: r:latest analysis/020_baseline_characteristics.R ./output/study_population_2019.csv ./output/tables/1_table_descriptive_2019.txt
    needs: [generate_cohort_2019, 010_data_management_2019]
    outputs: 
      moderately_sensitive:
        table1a: output/tables/1_table_descriptive_2019.txt

  020_baseline_characteristics_2020:
    run: r:latest analysis/020_baseline_characteristics.R ./output/study_population_2020.csv ./output/tables/1a_table_descriptive_2020.txt
    needs: [generate_cohort_2020, 010_data_management_2020]
    outputs: 
      moderately_sensitive:
        table1b: output/tables/1a_table_descriptive_2020.txt

  020_baseline_characteristics_2wave:
    run: r:latest analysis/020_baseline_characteristics.R ./output/study_population_2wave.csv ./output/tables/1b_table_descriptive_2wave.txt
    needs: [generate_cohort_2wave, 010_data_management_2wave]
    outputs: 
      moderately_sensitive:
        table1c: output/tables/1b_table_descriptive_2wave.txt

  020_baseline_characteristics_2021:
    run: r:latest analysis/020_baseline_characteristics.R ./output/study_population_2021.csv ./output/tables/1c_table_descriptive_2021.txt
    needs: [generate_cohort_2021, 010_data_management_2021]
    outputs: 
      moderately_sensitive:
        table1d: output/tables/1c_table_descriptive_2021.txt

  020_baseline_characteristics_1wave_new:
    run: r:latest analysis/020_baseline_characteristics.R ./output/study_population_new_2020.csv ./output/tables/1d_table_descriptive_1wave_new.txt
    needs: [generate_cohort_2020, 010_data_management_2020]
    outputs: 
      moderately_sensitive:
        table1b: output/tables/1d_table_descriptive_1wave_new.txt

  020_baseline_characteristics_2wave_new:
    run: r:latest analysis/020_baseline_characteristics.R ./output/study_population_new_2wave.csv ./output/tables/1e_table_descriptive_2wave_new.txt
    needs: [generate_cohort_2wave, 010_data_management_2wave]
    outputs: 
      moderately_sensitive:
        table1b: output/tables/1e_table_descriptive_2wave_new.txt

  030_descriptive_mortality_rates:
    run: r:latest analysis/030_descriptive_mortality_rates.R 
    needs: [generate_measures_cohorts, generate_measures]
    outputs: 
      moderately_sensitive:
        2_table_descriptive: output/tables/2*
        2_plot_descriptive: output/plots/2*

  035_comparative_mortality_rates:
    run: r:latest analysis/035_comparative_mortality_rates.R 
    needs: [generate_measures_cohorts, generate_measures]
    outputs: 
      moderately_sensitive:
        3_table_comparative: output/tables/3*
        3_plot_comparative: output/plots/3*

  040_cause_of_death:
    run: r:latest analysis/040_cause_of_death.R 
    needs: [generate_measures_cohorts]
    outputs: 
      moderately_sensitive:
        4a_table_allcauses_ch: output/tables/4a_table_allcauses_ch.txt
        4c_table_nccauses_ch: output/tables/4c_table_nccauses_ch.txt
        4a_plot_allcauses_ch: output/plots/4a_plot_allcauses_ch.png
        4c_plot_nccauses_ch: output/plots/4c_plot_nccauses_ch.png

  050_standardisation:
    run: r:latest analysis/050_standardisation.R 
    needs: [generate_measures_cohorts, generate_measures]
    outputs: 
      moderately_sensitive:
        5_table_standardised: output/tables/5*
        5_plot_standardised: output/plots/5*
        6_table_cmr: output/tables/6*
        6_plot_cmr: output/plots/6*

  055_standardisation_age_stratified:
    run: r:latest analysis/055_standardisation_age_stratified.R 
    needs: [generate_measures_cohorts, generate_measures]
    outputs: 
      moderately_sensitive:
        7_table_standardised: output/tables/7*
        7_plot_standardised: output/plots/7*
        8_table_cmr: output/tables/8* 
        8_plot_cmr: output/plots/8*

# SENSITIVITY ANALYSES 

  generate_sensitivity_measures_cohorts:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_sensitivity --index-date-range "2019-02-01 to 2021-03-31 by month"
    outputs:
      highly_sensitive:
        sens_cohort_measures: output/input_sensitivity_*.csv

  generate_sensitivity_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition_sensitivity
    needs: [generate_sensitivity_measures_cohorts]
    outputs:
      highly_sensitive:
        SENS_measure4: output/measure_SENS_covid_death_sex_age_five.csv
        SENS_measure5: output/measure_SENS_allcause_death_sex_age_five.csv
        SENS_measure6: output/measure_SENS_noncovid_death_sex_age_five.csv

  S020_sensitivity_baseline_characteristics_chdetail:
    run: r:latest analysis/S020_sensitivity_baseline_characteristics_chdetail.R ./output/study_population_2019.csv ./output/tables/S1_table_descriptive_2019.txt
    needs: [generate_cohort_2019, 010_data_management_2019]
    outputs: 
      moderately_sensitive:
        S_table1: output/tables/S1_table_descriptive_2019.txt

  S050_sensitivity_standardisation_chdetail:
    run: r:latest analysis/S050_sensitivity_standardisation_chdetail.R 
    needs: [generate_measures_cohorts, generate_measures]
    outputs: 
      moderately_sensitive:
        S2_table_standardised: output/tables/S2*
        S2_plot_standardised: output/plots/S2*

  S030_sensitivity_descriptive_test_admission:
    run: r:latest analysis/S030_sensitivity_descriptive_test_admission.R 
    needs: [generate_measures_cohorts, generate_measures]
    outputs: 
      moderately_sensitive:
        S3_table_descriptive: output/tables/S3*
        S3_plot_descriptive: output/plots/S3*

  S050_sensitivity_standardisation_testing_admission:
    run: r:latest analysis/S050_sensitivity_standardisation_testing_admission.R 
    needs: [generate_measures_cohorts, generate_measures]
    outputs: 
      moderately_sensitive:
        S5_table_standardised: output/tables/S5*
        S5_plot_standardised: output/plots/S5*
        S6_table_cmr: output/tables/S6*
        S6_plot_cmr: output/plots/S6*

  S050_sensitivity_standardisation_expanded_chome:
    run: r:latest analysis/S050_sensitivity_standardisation_expanded_chome.R 
    needs: [generate_sensitivity_measures_cohorts, generate_sensitivity_measures]
    outputs: 
      moderately_sensitive:
        S7_table_standardised: output/tables/S7*
        S7_plot_standardised: output/plots/S7*
        S8_table_cmr: output/tables/S8*
        S8_plot_cmr: output/plots/S8*

  generate_comorb_measures_cohorts:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_comorbidities --index-date-range "2019-02-01 to 2021-03-31 by month"
    outputs:
      highly_sensitive:
        comorb_cohort_measures: output/input_comorbidities*

  generate_comorb_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition_comorbidities
    needs: [generate_comorb_measures_cohorts]
    outputs:
      moderately_sensitive:
        dementia: output/measure_COMORB_dementia.csv 
        stroke: output/measure_COMORB_stroke.csv 
        cancer: output/measure_COMORB_cancer.csv 
        chronic_cardiac_disease: output/measure_COMORB_chronic_cardiac_disease.csv 
        chronic_respiratory_disease: output/measure_COMORB_chronic_respiratory_disease.csv 
        chronic_liver_disease: output/measure_COMORB_chronic_liver_disease.csv 
        diabetes: output/measure_COMORB_diabetes.csv 

  S_comorbidity_plots:
    run: r:latest analysis/S_comorbidity_plots.R 
    needs: [generate_comorb_measures]
    outputs: 
      moderately_sensitive:
        S9_plots*: output/plots/S9*


